version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - “27017:27017”
    
  case_study_02:
    image: ${DOCKER_REGISTRY-}casestudy02
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CustomerDatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

